version: '3'
services:
 mongodb:
   image : mongo
   restart: always
   ports:
     - "27017:27017"
   container_name: mongo-container
   network_mode: host
 spring:
   image: spring-boot
   restart: always
   build:
     SpringBootAssignment2/
   container_name: spring-docker
   network_mode: host
   depends_on: 
     - mongodb
     - zuul
     - Eurekaserver
   ports:
     - 8082:8082
 zuul:
    image: zuul
    restart: always
    build:
      zuul/
    container_name: zuul-container
    network_mode: host
    ports:
      - 8061:8061
    expose:
      - 8061


 Eurekaserver:
    image: eureka
    restart: always
    build:
      EurekaServer/
    container_name: eureka-container
    network_mode: host
    ports:
      - 8062:8062
    expose:
      - 8062

